name: Merge TXT Files

on:
  schedule:
    - cron: '0 1 * * *'  # 每天01:00 UTC运行一次
    - cron: '0 8 * * *'  # 每天08:00 UTC运行一次
    - cron: '0 15 * * *'  # 每天15:00 UTC运行一次
    - cron: '0 22 * * *'  # 每天22:00 UTC运行一次
  workflow_dispatch:  # 允许手动触发
  
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Merge TXT Files
      run: python mergefiles.py
      env:
        URL1: "https://cf.trackerslist.com/best.txt"  # 填写第一个txt文件的URL
        URL2: "https://github.com/ngosang/trackerslist/raw/master/trackers_best.txt"  # 填写第二个txt文件的URL
        URL3: "https://github.com/ngosang/trackerslist/raw/master/trackers_best_ip.txt"  # 填写第三个txt文件的URL
        Name: "tracker_all.txt"

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add tracker_all.txt
        git commit -m '更新tracker'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
